#!/usr/bin/env node
"use strict";
const assert=require("assert"),fs=require("fs"),http=require("http"),os=require("os"),path=require("path");
const ROOT=path.resolve(__dirname,"../.."),endpoint=process.env.DUALSUB_CDP_URL||"http://172.19.0.33:9222";
const publicHost=process.env.DUALSUB_REPLAY_HOST||Object.values(os.networkInterfaces()).flat().find(x=>x&&x.family==="IPv4"&&!x.internal&&/^172\./.test(x.address))?.address||"127.0.0.1";
class CDP{constructor(ws){this.ws=ws;this.id=0;this.pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(!m.id||!this.pending.has(m.id))return;const {resolve,reject}=this.pending.get(m.id);this.pending.delete(m.id);m.error?reject(new Error(m.error.message)):resolve(m.result)}}send(method,params={},sessionId){return new Promise((resolve,reject)=>{const id=++this.id;this.pending.set(id,{resolve,reject});this.ws.send(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})}))})}}
function serve(){const allowed=new Set(["popup.html","popup.js","core.js"]);return new Promise(resolve=>{const server=http.createServer((req,res)=>{const name=new URL(req.url,"http://x").pathname.replace(/^\//,"")||"popup.html";if(!allowed.has(name)){res.writeHead(404);return res.end("not found")}res.setHeader("content-type",name.endsWith(".html")?"text/html; charset=utf-8":"text/javascript; charset=utf-8");fs.createReadStream(path.join(ROOT,name)).pipe(res)});server.listen(0,"0.0.0",()=>resolve(server))})}
async function connect(){const v=await fetch(endpoint+"/json/version").then(r=>r.json());const ws=new WebSocket(v.webSocketDebuggerUrl.replace(/ws:\/\/[^/]+/,endpoint.replace(/^http/,"ws")));await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});return new CDP(ws)}
const bootstrap=String.raw`(()=>{const messages=[];let completed=false,cancelMode=false,cancelled=false,polls=0;window.__popupHarness={messages,downloads:[],confirms:[],resetForCancel(){completed=false;cancelMode=true;cancelled=false;polls=0},snapshot(){return{messages:messages.slice(),downloads:this.downloads.slice(),confirms:this.confirms.slice(),completed,cancelled,polls}}};window.confirm=text=>(window.__popupHarness.confirms.push(String(text)),true);URL.createObjectURL=()=>"blob:dualsub-popup-test";URL.revokeObjectURL=()=>{};HTMLAnchorElement.prototype.click=function(){window.__popupHarness.downloads.push({download:this.download,href:this.href})};const progress=status=>({ok:true,id:"srt-popup-test",status,totalUnits:2,completedUnits:completed?2:0,completedBatches:completed?1:0,totalBatches:1,usage:{promptTokens:completed?20:0,completionTokens:completed?8:0,totalTokens:completed?28:0,requests:completed?1:0}});const respond=message=>{messages.push(JSON.parse(JSON.stringify(message)));if(message.type==="get-state")return{ok:true,videoId:"fixture-video",tracks:[],apiUsage:{promptTokens:0,completionTokens:0,totalTokens:0,requests:0}};if(message.type==="export-srt")return completed?{ok:true,videoId:"fixture-video",sourceFingerprint:"fixture-fingerprint",units:[{startMs:0,endMs:1000,originalText:"first source",translation:"第一条译文"},{startMs:1000,endMs:2000,originalText:"second source",translation:"第二条译文"}]}:{ok:false,missingUnits:2,totalUnits:2};if(message.type==="prepare-full-srt")return progress("running");if(message.type==="full-srt-status"){polls++;if(cancelled)return progress("cancelled");if(!cancelMode&&polls>=2)completed=true;return progress(completed?"completed":"running")}if(message.type==="cancel-full-srt"){cancelled=true;return progress("cancelling")}return{ok:true}};window.chrome={runtime:{lastError:null},storage:{local:{get(_k,cb){cb({})},set(_v,cb){if(cb)cb()}}},tabs:{query(_q,cb){cb([{id:1,url:"https://www.youtube.com/watch?v=fixture-video"}])},sendMessage(_id,m,cb){setTimeout(()=>cb(respond(m)),0)}}}})();`;
async function evaluate(cdp,sid,expression){const out=await cdp.send("Runtime.evaluate",{expression,awaitPromise:true,returnByValue:true},sid);if(out.exceptionDetails)throw new Error(out.exceptionDetails.text||"evaluation failed");return out.result.value}
async function waitFor(cdp,sid,expr,label,timeout=5000){const end=Date.now()+timeout;while(Date.now()<end){if(await evaluate(cdp,sid,expr))return;await new Promise(r=>setTimeout(r,50))}throw new Error(`timeout waiting for ${label}`)}
(async()=>{const server=await serve(),cdp=await connect();let sid;try{const target=await cdp.send("Target.createTarget",{url:"about:blank"});sid=(await cdp.send("Target.attachToTarget",{targetId:target.targetId,flatten:true})).sessionId;await cdp.send("Page.enable",{},sid);await cdp.send("Runtime.enable",{},sid);await cdp.send("Page.addScriptToEvaluateOnNewDocument",{source:bootstrap},sid);await cdp.send("Page.navigate",{url:`http://${publicHost}:${server.address().port}/popup.html`},sid);await waitFor(cdp,sid,"document.readyState==='complete'&&!!window.__popupHarness","popup init");await evaluate(cdp,sid,"document.getElementById('exportSrtBtn').click()");await waitFor(cdp,sid,"window.__popupHarness.downloads.length===1","full SRT export");const exported=await evaluate(cdp,sid,"window.__popupHarness.snapshot()");assert.equal(exported.confirms.length,1);assert.match(exported.confirms[0],/Token|费用/);assert.ok(exported.messages.some(m=>m.type==="prepare-full-srt"&&m.confirmed===true));assert.ok(exported.messages.filter(m=>m.type==="full-srt-status").length>=2);assert.match(exported.downloads[0].download,/\.srt$/);await evaluate(cdp,sid,"window.__popupHarness.resetForCancel();document.getElementById('exportSrtBtn').click()");await waitFor(cdp,sid,"getComputedStyle(document.getElementById('cancelSrtBtn')).display!=='none'","cancel control");await evaluate(cdp,sid,"document.getElementById('cancelSrtBtn').click()");await waitFor(cdp,sid,"window.__popupHarness.messages.some(m=>m.type==='cancel-full-srt')","cancel message");const cancelled=await evaluate(cdp,sid,"window.__popupHarness.snapshot()");assert.equal(cancelled.cancelled,true);assert.equal(cancelled.downloads.length,1);assert.equal(cancelled.confirms.length,2);console.log("PASS popup full-SRT confirm/progress/export/cancel")}finally{if(sid)await cdp.send("Target.detachFromTarget",{sessionId:sid}).catch(()=>{});cdp.ws.close();server.close()}})().catch(e=>{console.error(e.stack||e);process.exit(1)});
