#!/usr/bin/env node
"use strict";
const assert=require("assert"),http=require("http"),fs=require("fs"),path=require("path"),os=require("os");
const ROOT=path.resolve(__dirname,"../..");
const FIX=__dirname;
const endpoint=process.env.DUALSUB_CDP_URL||"http://172.19.0.33:9222";
const publicHost=process.env.DUALSUB_REPLAY_HOST||Object.values(os.networkInterfaces()).flat().find(x=>x&&x.family==="IPv4"&&!x.internal&&/^172\./.test(x.address))?.address||"127.0.0.1";
const scenarios=(process.env.DUALSUB_REPLAY_SCENARIOS||"happy,semantic-failure,prewarm-failure,seek-race").split(",");
for(const name of ["index.html","track.json","semantic.json"])assert.ok(fs.existsSync(path.join(FIX,name)),`missing fixture: ${name}`);
class CDP{constructor(ws){this.ws=ws;this.id=0;this.pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&this.pending.has(m.id)){const {resolve,reject}=this.pending.get(m.id);this.pending.delete(m.id);m.error?reject(new Error(m.error.message)):resolve(m.result)}}}send(method,params={},sessionId){return new Promise((resolve,reject)=>{const id=++this.id;this.pending.set(id,{resolve,reject});this.ws.send(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})}))})}}
const mime={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".json":"application/json; charset=utf-8"};
function fileFor(url){const p=new URL(url,"http://x").pathname;if(p==="/core.js"||p==="/isolated.js")return path.join(ROOT,p.slice(1));return path.join(FIX,p==="/"?"index.html":p.slice(1))}
function serve(){return new Promise(resolve=>{const s=http.createServer((req,res)=>{const f=fileFor(req.url);if(!f.startsWith(ROOT)||!fs.existsSync(f)){res.writeHead(404);return res.end("not found")}res.setHeader("content-type",mime[path.extname(f)]||"application/octet-stream");fs.createReadStream(f).pipe(res)});s.listen(0,"0.0.0",()=>resolve(s))})}
async function connect(){const version=await fetch(endpoint+"/json/version").then(r=>r.json());const ws=new WebSocket(version.webSocketDebuggerUrl.replace(/ws:\/\/[^/]+/,endpoint.replace(/^http/,"ws")));await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});return new CDP(ws)}
function check(name,r){assert.equal(r.finished,true,`${name}: replay did not finish`);assert.deepEqual(r.errors,[],`${name}: browser errors: ${r.errors}`);assert.equal(r.pauseCalls,0,`${name}: paused player`);const fallback=r.paints.find(x=>x.orig&&!x.trans);assert.ok(fallback,`${name}: fallback original with blank Chinese never painted`);const starts=r.events.filter(x=>x.type==="translation-start");const bilingualPaints=r.paints.filter(x=>x.orig&&x.trans&&x.sampleType==="periodic");const bilingual=bilingualPaints.at(-1);for(const paint of bilingualPaints){assert.ok(!paint.trans.includes("。"),`${name}: rendered Chinese subtitle contains forbidden full stop`);assert.ok(paint.orig.trim().split(/\s+/).length<=16,`${name}: rendered English screen exceeds 16 words`);assert.ok(paint.origFontPx>=paint.baseFontPx*0.85&&paint.transFontPx>=paint.baseFontPx*0.85,`${name}: renderer hid bad segmentation with tiny text`);assert.ok(paint.playerRight>paint.playerLeft&&paint.origLeft>=paint.playerLeft-1&&paint.origRight<=paint.playerRight+1&&paint.transLeft>=paint.playerLeft-1&&paint.transRight<=paint.playerRight+1&&paint.origTop>=paint.playerTop-1&&paint.origBottom<=paint.playerBottom+1&&paint.transTop>=paint.playerTop-1&&paint.transBottom<=paint.playerBottom+1,`${name}: bilingual row escaped player viewport`)}
 if(name==="happy"){assert.equal(starts.length>0,true,"happy: semantic translation never started");assert.ok(bilingual,"happy: bilingual semantic unit never painted");assert.ok(starts[0].t>r.events.find(x=>x.type==="semantic-ready").t,"happy: translation started before semantic ready")}
 if(name==="semantic-failure"){assert.equal(starts.length,0,"semantic failure translated fallback cues");assert.equal(!!bilingual,false,"semantic failure replaced fallback")}
 if(name==="prewarm-failure"){assert.equal(starts.length>0,true,"prewarm failure was not exercised");assert.equal(!!bilingual,false,"failed prewarm replaced fallback")}
 if(name==="seek-race"){assert.ok(starts.length>=2,"seek race did not re-read playhead and prewarm new clip");assert.ok(bilingual&&bilingual.at>=7.4,"seek race installed stale clip")}}
(async()=>{const server=await serve(),port=server.address().port,cdp=await connect();try{for(const name of scenarios){const {targetId}=await cdp.send("Target.createTarget",{url:"about:blank"});const {sessionId}=await cdp.send("Target.attachToTarget",{targetId,flatten:true});await cdp.send("Runtime.enable",{},sessionId);await cdp.send("Page.navigate",{url:`http://${publicHost}:${port}/?scenario=${name}`},sessionId);const deadline=Date.now()+6000;let report;while(Date.now()<deadline){await new Promise(r=>setTimeout(r,100));const out=await cdp.send("Runtime.evaluate",{expression:"window.__report||null",returnByValue:true},sessionId);report=out.result.value;if(report&&report.finished)break}check(name,report||{});await cdp.send("Target.closeTarget",{targetId});console.log(`PASS ${name}`)}console.log(`browser replay: ${scenarios.length}/${scenarios.length} scenarios passed`)}finally{server.close();cdp.ws.close()}})().catch(e=>{console.error(e.stack||e);process.exit(1)});