#!/usr/bin/env node
"use strict";
const assert=require("assert"),http=require("http"),fs=require("fs"),path=require("path"),os=require("os");
const ROOT=path.resolve(__dirname,"../..");
const FIX=__dirname;
const endpoint=process.env.DUALSUB_CDP_URL||"http://172.19.0.33:9222";
const publicHost=process.env.DUALSUB_REPLAY_HOST||Object.values(os.networkInterfaces()).flat().find(x=>x&&x.family==="IPv4"&&!x.internal&&/^172\./.test(x.address))?.address||"127.0.0.1";
const scenarios=(process.env.DUALSUB_REPLAY_SCENARIOS||"happy,semantic-long-fallback,semantic-slow-fallback,semantic-merge-repair,semantic-failure,semantic-partial-install,fallback-merge-repair,fallback-in-cap-merge,prewarm-failure,seek-race,semantic-cache").split(",");
for(const name of ["index.html","track.json","semantic.json"])assert.ok(fs.existsSync(path.join(FIX,name)),`missing fixture: ${name}`);
class CDP{constructor(ws){this.ws=ws;this.id=0;this.pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&this.pending.has(m.id)){const {resolve,reject}=this.pending.get(m.id);this.pending.delete(m.id);m.error?reject(new Error(m.error.message)):resolve(m.result)}}}send(method,params={},sessionId){return new Promise((resolve,reject)=>{const id=++this.id;this.pending.set(id,{resolve,reject});this.ws.send(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})}))})}}
const mime={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".json":"application/json; charset=utf-8"};
function fileFor(url){const p=new URL(url,"http://x").pathname;if(p==="/core.js"||p==="/isolated.js")return path.join(ROOT,p.slice(1));return path.join(FIX,p==="/"?"index.html":p.slice(1))}
function serve(){return new Promise(resolve=>{const s=http.createServer((req,res)=>{const f=fileFor(req.url);if(!f.startsWith(ROOT)||!fs.existsSync(f)){res.writeHead(404);return res.end("not found")}res.setHeader("content-type",mime[path.extname(f)]||"application/octet-stream");fs.createReadStream(f).pipe(res)});s.listen(0,"0.0.0",()=>resolve(s))})}
async function connect(){const version=await fetch(endpoint+"/json/version").then(r=>r.json());const ws=new WebSocket(version.webSocketDebuggerUrl.replace(/ws:\/\/[^/]+/,endpoint.replace(/^http/,"ws")));await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});return new CDP(ws)}
function check(name,r){assert.equal(r.finished,true,`${name}: replay did not finish`);assert.deepEqual(r.errors,[],`${name}: browser errors: ${r.errors}`);assert.equal(r.pauseCalls,0,`${name}: paused player`);const fallback=r.paints.find(x=>x.orig&&!x.trans);assert.ok(fallback,`${name}: fallback original with blank Chinese never painted`);const starts=r.events.filter(x=>x.type==="translation-start");const ready=r.events.filter(x=>x.type==="translation-ready");const expectedResponses=name==="fallback-merge-repair"||name==="fallback-in-cap-merge"||name==="semantic-merge-repair"?2:ready.length;if(name!=="semantic-slow-fallback"){assert.equal(r.apiUsage&&r.apiUsage.requests,expectedResponses,`${name}: runtime usage missed a completed translation response`);assert.equal(r.apiUsage&&r.apiUsage.totalTokens,expectedResponses*14,`${name}: runtime usage total drift`);}const bilingualPaints=r.paints.filter(x=>x.orig&&x.trans&&x.trans!=="翻译中…"&&x.trans!=="翻译失败"&&x.sampleType==="periodic");const bilingual=bilingualPaints.at(-1);for(const paint of bilingualPaints){assert.match(paint.trans,/[\u3400-\u9fff]/,`${name}: bilingual paint did not contain real CJK translation`);assert.notEqual(paint.trans,"翻译中…",`${name}: loading placeholder counted as translation`);assert.notEqual(paint.trans,"翻译失败",`${name}: failure placeholder counted as translation`);assert.ok(!paint.trans.includes("。"),`${name}: rendered Chinese subtitle contains forbidden full stop`);const wordLimit=r.segmentationMode==="fallback-translation"?14:12;assert.ok(paint.orig.trim().split(/\s+/).length<=wordLimit,`${name}: rendered English screen exceeds ${wordLimit} words`);assert.ok(paint.origFontPx>=paint.baseFontPx*0.85&&paint.transFontPx>=paint.baseFontPx*0.85,`${name}: renderer hid bad segmentation with tiny text`);assert.ok(paint.playerRight>paint.playerLeft&&paint.origLeft>=paint.playerLeft-1&&paint.origRight<=paint.playerRight+1&&paint.transLeft>=paint.playerLeft-1&&paint.transRight<=paint.playerRight+1&&paint.origTop>=paint.playerTop-1&&paint.origBottom<=paint.playerBottom+1&&paint.transTop>=paint.playerTop-1&&paint.transBottom<=paint.playerBottom+1,`${name}: bilingual row escaped player viewport`)}
 if(name==="happy"){assert.equal(r.segmentationMode,"semantic","happy path did not install semantic mode");assert.equal(starts.length>0,true,"happy: semantic translation never started");assert.ok(bilingual,"happy: bilingual semantic unit never painted");assert.ok(starts[0].t>r.events.find(x=>x.type==="semantic-ready").t,"happy: translation started before semantic ready")}
 if(name==="semantic-long-fallback"){const semanticReady=r.events.find(x=>x.type==="semantic-ready");assert.equal(semanticReady,undefined,"long semantic fixture should still be pending when report finishes");assert.equal(r.segmentationMode,"fallback-translation","long semantic hang did not remain in fallback translation mode");assert.equal(starts.length>0,true,"long semantic hang did not start fallback translation promptly");assert.ok(starts[0].t<1000,"fallback translation did not start within 1s during long semantic hang");assert.ok(bilingual,"long semantic hang left current playback English-only");assert.ok(r.paints.some(x=>x.orig&&x.nativeHidden&&x.nativeDisplay==="none"),"native captions were not hidden during long semantic hang fallback paint")}
 if(name==="semantic-slow-fallback"){const beforeSemanticReady=r.events.find(x=>x.type==="semantic-ready");const fallbackBilingual=bilingualPaints.find(x=>!beforeSemanticReady||x.t<beforeSemanticReady.t);assert.equal(starts.length>0,true,"slow semantic restore did not start fallback translation promptly");assert.ok(fallbackBilingual,"slow semantic restore left current playback English-only before semantic was ready");assert.ok(starts[0].t<1000,"fallback translation did not start within 1s while semantic restore was still pending");assert.ok(r.paints.some(x=>x.orig&&x.nativeHidden&&x.nativeDisplay==="none"),"YouTube native captions were not hidden while DualSub fallback/original text was visible");assert.equal(r.segmentationMode,"semantic","semantic did not atomically take over after slow fallback translation completed");assert.ok(r.events.some(x=>x.type==="translation-ready"&&x.mode==="fallback-translation"),"slow path did not complete a fallback translation before semantic takeover race window");assert.ok(bilingual&&bilingual.orig&&bilingual.trans,"semantic takeover should leave a valid bilingual paint, not stale blank fallback");assert.ok(r.nativeRestored,"native YouTube captions were not restored after DualSub teardown")}
 if(name==="semantic-merge-repair"){assert.equal(r.segmentationMode,"semantic","semantic repair scenario did not install semantic mode");assert.equal(r.lockedRepairMode,"semantic","production caller did not pass semantic mode into repair");assert.equal(r.lockedRepairRequests,2,"in-cap semantic MERGE_PREV did not perform exactly one locked retry");assert.deepEqual(r.lockedRepairCueWords,[4,4],"semantic locked retry merged or changed original cue boundaries");const painted=new Set(bilingualPaints.map(x=>x.orig));assert.ok(painted.has("Let me explain that")&&painted.has("this kettle works reliably"),"both original semantic screens were not painted separately")}
 if(name==="semantic-failure"){assert.equal(r.segmentationMode,"fallback-translation","semantic failure did not remain in fallback translation mode");assert.equal(starts.length>0,true,"semantic failure did not start fallback translation");assert.ok(bilingual,"semantic failure left the page permanently English-only");assert.match(bilingual.trans,/[\u3400-\u9fff]/,"semantic failure did not paint real CJK translation")}
 if(name==="semantic-partial-install"){assert.equal(r.segmentationMode,"fallback-translation","partial install failure did not enter fallback translation mode");assert.ok(r.events.some(x=>x.type==="semantic-partial-install"),"semantic install failure was not exercised");assert.ok(starts.length>=2,"partial semantic install did not resume fallback translation via periodic prefetch");assert.ok(bilingual,"partial semantic install did not self-recover to bilingual rendering");assert.match(bilingual.trans,/[\u3400-\u9fff]/,"partial semantic install did not paint real CJK translation")}
 if(name==="fallback-merge-repair"){assert.equal(r.segmentationMode,"fallback-translation","repair scenario did not enter fallback translation mode");assert.equal(r.lockedRepairMode,"fallback-translation","production caller did not pass fallback mode into repair");assert.equal(r.lockedRepairRequests,2,"13+2 fallback MERGE_PREV did not perform exactly one locked retry");assert.ok(bilingual&&bilingual.orig.trim().split(/\s+/).length===13,"natural 13-word fallback screen was not preserved and painted")}
 if(name==="fallback-in-cap-merge"){assert.equal(r.segmentationMode,"fallback-translation","in-cap repair did not enter fallback translation mode");assert.equal(r.lockedRepairMode,"fallback-translation","production caller did not pass fallback mode into in-cap repair");assert.equal(r.lockedRepairRequests,2,"7+7 fallback MERGE_PREV did not perform exactly one merge retry");assert.deepEqual(r.lockedRepairCueWords,[14],"7+7 fallback did not install one exact 14-word merged cue");assert.ok(bilingual&&bilingual.orig.trim().split(/\s+/).length===14,"merged 14-word fallback screen was not painted")}
 if(name==="prewarm-failure"){assert.equal(starts.length>0,true,"prewarm failure was not exercised");assert.equal(!!bilingual,false,"failed prewarm replaced fallback")}
 if(name==="seek-race"){assert.ok(starts.length>=2,"seek race did not re-read playhead and prewarm new clip");assert.ok(bilingual&&bilingual.at>=7.4,"seek race installed stale clip")}
 if(name==="semantic-cache"){assert.equal(r.segmentationMode,"semantic","semantic cache path did not finish in semantic mode");const restores=r.events.filter(x=>x.type==="semantic-start");assert.equal(restores.length,2,"semantic cache missed when returning to the same video")}}
(async()=>{const server=await serve(),port=server.address().port,cdp=await connect();try{for(const name of scenarios){const {targetId}=await cdp.send("Target.createTarget",{url:"about:blank"});const {sessionId}=await cdp.send("Target.attachToTarget",{targetId,flatten:true});await cdp.send("Runtime.enable",{},sessionId);await cdp.send("Page.navigate",{url:`http://${publicHost}:${port}/?scenario=${name}`},sessionId);const deadline=Date.now()+6000;let report;while(Date.now()<deadline){await new Promise(r=>setTimeout(r,100));const out=await cdp.send("Runtime.evaluate",{expression:"window.__report||null",returnByValue:true},sessionId);report=out.result.value;if(report&&report.finished)break}check(name,report||{});await cdp.send("Target.closeTarget",{targetId});console.log(`PASS ${name}`)}console.log(`browser replay: ${scenarios.length}/${scenarios.length} scenarios passed`)}finally{server.close();if(typeof server.closeAllConnections==="function")server.closeAllConnections();cdp.ws.close()}})().catch(e=>{console.error(e.stack||e);process.exit(1)});